# Generated by Django 3.2.3 on 2021-05-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usrename',
            field=models.CharField(max_length=32, verbose_name='사용자명'),
        ),
    ]
