# Generated by Django 3.2.3 on 2021-05-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_usrename_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '일반 사용자', 'verbose_name_plural': '일반 사용자'},
        ),
        migrations.AddField(
            model_name='user',
            name='useremail',
            field=models.EmailField(default='python@testpython.co.kr', max_length=128, verbose_name='사용자이메일'),
            preserve_default=False,
        ),
    ]
